//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyFileExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TinyFileExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;div id=&quot;custom-context-menu&quot;&gt;
        ///    &lt;div class=&quot;item&quot;&gt;
        ///        &lt;i&gt;&lt;/i&gt; Delete
        ///    &lt;/div&gt;
        ///    &lt;div class=&quot;item&quot;&gt;
        ///        &lt;i&gt;&lt;/i&gt; Copy
        ///    &lt;/div&gt;
        ///
        ///&lt;/div&gt;
        ///.
        /// </summary>
        public static string components {
            get {
                return ResourceManager.GetString("components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a document.addEventListener(&apos;DOMContentLoaded&apos;, function () {
        ///
        ///   
        ///
        ///    // Seleciona todos os elementos com a classe &apos;arrow&apos;
        ///    const arrows = document.querySelectorAll(&apos;.arrow&apos;);
        ///
        ///    // Adiciona um event listener de clique a cada &apos;arrow&apos;
        ///    arrows.forEach(function (arrow) {
        ///        arrow.addEventListener(&apos;click&apos;, function (event) {
        ///            event.stopPropagation();
        ///
        ///            // Seleciona o elemento pai com a classe &apos;folder&apos;
        ///            const folder = arrow.closest(&apos;.folder&apos;);
        ///          [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string tinyFileExplorerScript {
            get {
                return ResourceManager.GetString("tinyFileExplorerScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a li {
        ///    user-select: none; /* Para navegadores modernos */
        ///    -webkit-user-select: none; /* Para navegadores baseados em WebKit */
        ///    -moz-user-select: none; /* Para Firefox */
        ///    -ms-user-select: none; /* Para Internet Explorer/Edge */
        ///}
        ///
        ///.directory-container {
        ///    font-size: 17px;
        ///}
        ///
        ///.content-name {
        ///    margin-bottom: 10px; /* Ajuste o valor conforme necessário */
        ///}
        ///
        ///.folder .content-name {
        ///    margin-bottom: 15px; /* Ajuste o valor conforme necessário */
        ///}
        ///
        ///.folder-icon {
        ///    widt [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string tinyFileExplorerStyle {
            get {
                return ResourceManager.GetString("tinyFileExplorerStyle", resourceCulture);
            }
        }
    }
}
